Repository canonical/flask-k8s-operator, pull requests merged in 2023-10, with the labels that each got.

#57 Change the service from flask-app to flask
  src/charm.py
  src/constants.py
  src/flask_app.py
  tests/unit/test_charm.py
Labels: Libraries: OK

#59 Add a new log panel in the Grafana dashboard
  src/charm_state.py
  src/grafana_dashboards/flask.json
  test_db_rock/alembic/versions/eca6177bd16a_initial_migration.py
  test_db_rock/app.py
  tests/integration/conftest.py
Labels: Libraries: Out of sync, trivial

#60 Switch to using edge runners
  .github/workflows/test.yaml
Labels: Libraries: Out of sync, trivial

#63 ci(digest): Add digest pinning
  renovate.json
Labels: Libraries: OK, trivial

#64 Fix the error log when database migration failed
  src/database_migration.py
Labels: bug, Libraries: OK
